# Generated by Django 4.0.2 on 2022-02-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='snippetfile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.CharField(default='', max_length=25000),
        ),
    ]
