# Generated by Django 3.2.9 on 2021-12-05 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=25000)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='snippets.snippet')),
            ],
        ),
    ]
