# Generated by Django 3.2.5 on 2021-12-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('SnippetId', models.AutoField(primary_key=True, serialize=False)),
                ('SnippetName', models.CharField(max_length=255)),
                ('SnippetDescription', models.CharField(max_length=25000)),
            ],
        ),
    ]
