# Generated by Django 3.2.9 on 2021-12-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippetfile'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='snippets',
            field=models.ManyToManyField(related_name='technologies', to='snippets.Snippet'),
        ),
    ]
